### ISSUE TITLE
Suggestions: Result Table and Class for Racers

### ISSUE THREAD

**Issue by peisel** [polyvision/EasyRaceLapTimer#12]
Look at the Screenshot ;-) ... there are some ideas that would be nice in easyracelaptimer also ...
![12313620_1663570637251509_2880877569649852142_n](https://cloud.githubusercontent.com/assets/6499781/11564257/8cd9cef8-99d8-11e5-94d1-808aacbfe0a6.jpg)

**Comment by polyvision** [comment]
done ;)
