### ISSUE TITLE
Monitor API - service discovery

### ISSUE THREAD

**Issue by FieserKiller** [polyvision/EasyRaceLapTimer#23]
Finding the LapTimer host in a network is a game of luck. In the majority of cases its needed to identify the server and type its IP into a client manually. Could we make the server detectable? I'm thinking of regular udp broadcasts or running a service like NSD or Bonjour.

**Comment by polyvision** [comment]
Sure! The UDP broadcasts should be no problem. However, I don't have experience with NSD or Bonjour. Maybe these two services are a better option? Dunno.

**Comment by peisel** [comment]
Couldnt we set a landing page like at hotspots where you redirected after connect with the wifi ... So you didnt must type the ip

**Comment by polyvision** [comment]
added, UDP json broadcast on port 3333
