### ISSUE TITLE
Auto update race panel

### ISSUE THREAD

**Issue by cmenard** [polyvision/EasyRaceLapTimer#26]
Currently one has to manually refresh the page to get updates during a race.  I'm wondering if we could use something like this https://github.com/chrismccord/sync to automatically update the page during a race session.

**Comment by polyvision** [comment]
this gem looks interesting, will check it out

**Comment by PProvost** [comment]
Honestly, I quick-n-dirty solution would be to use client-side auto refresh logic. 

Something simple like:

    <meta http-equiv="refresh" content="10" />

Would do nicely.

**Comment by polyvision** [comment]
fixed in upcomming v0.4b, made a quick solution. The gem also uses websockets. I would have the same problem like now with actioncable (also websockets).
