### ISSUE TITLE
How to update the files in Raspberry PI

### ISSUE THREAD

**Issue by peisel** [polyvision/EasyRaceLapTimer#3]
It would be nice to have a description/manual how to simple update the solution on the Raspberry Pi to latest version.

**Comment by PProvost** [comment]
I agree. For my most recent update, after pulling the new source, I had to reset the database using the rake commands in the setup guide. It is probably a good idea to explain that to people.

**Comment by polyvision** [comment]
wrote update docs for 0.3 ;)
