### ISSUE TITLE
PDF Export didn't work in 0.4b2?

### ISSUE THREAD

**Issue by peisel** [polyvision/EasyRaceLapTimer#30]
"We're sorry, but something went wrong.
If you are the application owner check the logs for more information."

Perhaps - Add a Info to get the logs?

Updated via update.md description.

**Comment by polyvision** [comment]
Did u update via git pull? 
If yes:

cd ~/EasyRaceLapTimer
chmod +x web/bin/wkhtmltopdf

This was fixed in the image version.

**Comment by peisel** [comment]
ok this will i miss update allways over git pull ;-)

**Comment by peisel** [comment]
test - works
