### ISSUE TITLE
Upload Soundfiles doesn't work

### ISSUE THREAD

**Issue by peisel** [polyvision/EasyRaceLapTimer#4]
Test with short .wav files, .mp3 files. Upload Button don't work.

**Comment by polyvision** [comment]
fixed in upcomming v0.3

workaround for current version: go to sound page, reload the page, upload works. curious bug ;)

**Comment by PProvost** [comment]
I'm in 0.4b2 and unable to upload sound files using the webpage. Nothing helpful in the apache2 error log file, and nothing at all in the easyracelaptimer.error.log file.
