### ISSUE TITLE
How to Create a New Admin Account?

### ISSUE THREAD

**Issue by 135erHeli** [polyvision/EasyRaceLapTimer#55]
The Docs nowhere shows how to create a new Admin acount,why there is no Section via Configuration?How can i create a new Account?

**Comment by 135erHeli** [comment]
Hmm should be a Question that is Hard thats not in the Doku and nobody knows the answer.Ill found it by myself,but the Support here is like it is in Germany....This Project is boring, No Support and the Dokumentation as it is is Useful like the Support here.....

**Comment by polyvision** [comment]
At present, there's no way to easily add a new admin account. That's something we have to do.
