### ISSUE TITLE
Suggestion: Configure number of laps in a race

### ISSUE THREAD

**Issue by PProvost** [polyvision/EasyRaceLapTimer#6]
Instead of just providing a name for the race, we should also be able to set the number of laps in the race.

That way the system could tell you 1st, 2nd, and 3rd place, and even play a special sound when the winner crosses the finish line.

**Comment by polyvision** [comment]
this sounds good, will write it down on the todo list!

**Comment by peisel** [comment]
Yes this sounds good, i'm thinking about other race modes that could be fun ... like https://de.wikipedia.org/wiki/Einerverfolgung

**Comment by polyvision** [comment]
This one is done regarding the number of laps in competition mode, however I can't play sounds for first place at present
