### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by NicoLoco** [polyvision/EasyRaceLapTimer#62]
in the documentation, hardware.md points to a schematic for the transmitters version 0.3.1, but the link is broken
https://github.com/polyvision/EasyRaceLapTimer/blob/master/datasheets/easy_race_lap_timer_transponder_attiny85_rev3_schematic
error 404

**Comment by TimJC513** [comment]
I submitted pull request #64 with the fix for this.

**Comment by polyvision** [comment]
got merged, thanks!
