### ISSUE TITLE
Unable to create website login

### ISSUE THREAD

**Issue by NicoLoco** [polyvision/EasyRaceLapTimer#69]
I have pulled the latest version and recompiled, and started with a fresh database.
I can't see an option to register an account on the website, so I'm unable to login.

**Comment by polyvision** [comment]
There is no way to register outside the system. There's a default user: admin@easyracelaptimer.com with pw: defaultpw

After migrating & seeding the database this user exists. Then u can login with this user and add new users or change the default user. But the system does not allow to register from the outside.
