### ISSUE TITLE
IR-Daemon Install Issue

### ISSUE THREAD

**Issue by PProvost** [polyvision/EasyRaceLapTimer#7]
I'd like to have someone else confirm whether this is actually an issue or something specific to my configuration...

On my RPi I boot to console, not the desktop (as configured in raspi-config). I found that putting the IR Daemon into /etc/rc.local as described in the setup guide was blocking the login from finishing. I suspect it is caused by an incorrect exit code from the program, but I'm not sure.

As I was researching this, I found the following articles to be helpful:

* http://www.raspberry-projects.com/pi/pi-operating-systems/raspbian/auto-running-programs
* http://www.raspberry-projects.com/pi/pi-operating-systems/raspbian/scripts
* http://raspberrypi.stackexchange.com/questions/11752/issue-with-rc-local-on-boot
* http://askubuntu.com/questions/239600/why-doesnt-rc-local-run-all-my-commands-and-what-can-i-do-about-it

Using the "Quick Fix" from the last article, I changed my /etc/rc.local line to the following, and now it gets through to the login prompt:

    (sleep 1; /home/pi/EasyRaceLapTimer/ir_daemon/ir_daemon &) || /bin/true

If anyone else has a better solution, please let me know.

**Comment by polyvision** [comment]
fixed this with your fix in the 0.3er image
