### ISSUE TITLE
Race Restart Button didn't work?!

### ISSUE THREAD

**Issue by peisel** [polyvision/EasyRaceLapTimer#9]
Update via commands - not the complete image.

I use a buzzer button - contact closed as long i pressed the button. Connected to 23(signal),25(gnd) pin. Did i miss something?
![wp_20151129_12_39_19_rich_li](https://cloud.githubusercontent.com/assets/6499781/11460097/477062fe-96e6-11e5-8e7e-f713a98180b5.jpg)

**Comment by peisel** [comment]
Sorry i see it in my own picture ... wire wrong ... ;-)

**Comment by peisel** [comment]
Sorry wiring is ok - issue exist

**Comment by polyvision** [comment]
same here, try again after the restart ;)

**Comment by peisel** [comment]
hmm ... how should it work ... i thought the current race will reset? or how should this button work?

**Comment by polyvision** [comment]
if u push the button, a new race will get started

**Comment by peisel** [comment]
Ich bekomme es nicht zum laufen ... der schalter verbindet pin 23 und gnd solange wie ich ihn gedrückt halte. Ich hatte einmal einen Eintrag "Race November 29, 2015 22:40	0	0	0.0s		0.0s" dies konnte ich aber nicht reproduzieren, Ich benutze img 0.2 mit dem manuellen update auf 0.3. Den Pin habe ich auch einmal mit Kabel auf gnd überbrückt aber dort das gleiche liegt also nicht am schalter.... ratlos

**Comment by polyvision** [comment]
Ich habe jetzt gerade nicht das Layout vor mir. Aber Du hast + an den PIN-Eingang gelegt? Hm, aber warte bis ich nachher nachschauen kann, bevor ich jetzt Mist rede ;)

**Comment by peisel** [comment]
Der Taster verbindet das Signal von PIN 23 (Rotes Kabel) mit GND Pin 25 (schwarzes Kabel) wenn er gedrückt wird, ich gehe davon aus etwas spinnt mit software oder pi nicht?

**Comment by polyvision** [comment]
wie lange drückst du denn? also 1sek muss gedrückt werden damit etwas passiert, ist so in der software programmiert

**Comment by peisel** [comment]
Keine Ahnung ... lange gedrückt, kurz gedrückt ... ich warte mal ab auf 0.4 ...

**Comment by peisel** [comment]
when i connect pin 23 and 24 for a second it works ... is it right? Pin 23 reacts when its connected with a + signal?
