### ISSUE TITLE
Unable to fetch files

### ISSUE THREAD

**Issue by stevelee10** [polyvision/EasyRaceLapTimer#94]
Hi hope you can help out, i have been following the setup guide, but its having some errors where it is unable to fetch some of the files from mirrordirector.raspian.org

is there a particular reason for this?

![20170527_210207](https://cloud.githubusercontent.com/assets/26190349/26524094/3a74f08c-4320-11e7-98b4-1b7025f130cc.jpg)

**Comment by pandalion98** [comment]
Sometimes it's just down.

**Comment by stevelee10** [comment]
ill try it again tonight after work, just thought i would check i hadnt done anything stupid.

**Comment by pandalion98** [comment]
@stevelee10 If it's still down or if you want additional reliability, pick some mirrors from [https://www.raspbian.org/RaspbianMirrors](https://www.raspbian.org/RaspbianMirrors). It won't hurt to add a few more. Just follow the file format and you'll be fine.

After that, do an `apt-get update` and you should be good to go.

**Comment by stevelee10** [comment]
cheers, its still not playing, so ill give that ago, its only the 1 file it fails to fetch, bit annoying
cant access that site either i get a 504 gateway timeout

**Comment by stevelee10** [comment]
ok ive found another working mirror, how do i change mirror so that it looks at this one instead?

**Comment by stevelee10** [comment]
ive tried other mirrors im having loads of issues, my latest is it cant locate package libaprutill-dev

**Comment by stevelee10** [comment]
sorted now i think. thanks for the help
